### ISSUE TITLE
New Material design 2 support

### ISSUE THREAD

**Issue by vooze** [KeenRivals/chrome-developer-edition-dark#3]
Hi :)

Are you going to support the new Material design (2) in the future? I looks alright, but looking at this: https://github.com/KeenRivals/chrome-developer-edition-dark/issues/1, it seems to be happening again, with the new UI:

![image](https://user-images.githubusercontent.com/9928653/43070395-03d7e42a-8e70-11e8-9721-ead16ae03a40.png)

Picture taken from Canary 70. 

Thank you for a great theme !

**Comment by KeenRivals** [comment]
Thanks for putting this on the radar. I plan to support the new design. I will probably follow the path I did last time and keep the old theme for a few weeks so most Chromes can update first.

**Comment by vooze** [comment]
Awesome! Thank you.

**Comment by KeenRivals** [comment]
Development is happening in the [material-2 branch](https://github.com/KeenRivals/chrome-developer-edition-dark/tree/material-2). 

I've noticed that the chrome flag to enable material design 2 has a "refresh" and a "touchable refresh". The "touchable" version has even larger tabs. The new version of the theme's blue highlight is too small in the touchable version. For now I think I'll plan to not support the touchable interface. The regular version looks fine now. 

# "Refresh" Theme
![](https://i.imgur.com/3lM9BAM.png)

# "Touchable Refresh" Theme

![](https://i.imgur.com/kbhfnmm.png)

**Comment by vooze** [comment]
That's good to see :)

Let's just hope that chrome will keep the feature to choose and hope they wont force the touch interface. 

On a sidenode, would it be possible to make the favicon's background white, like vivaldi does? It really helps when it's dark favicons (lige github)

**Comment by KeenRivals** [comment]
I don't think I can change the favicon background. Chrome themes are depressingly simple. You provide images for the tab bg, tab fg, and frame, then some text/highlight colors. You can't do anything interesting or dynamic at all as far as I can tell.

**Comment by vooze** [comment]
Yeah I figured, just wanted to check. Thanks for the answer and your work.

**Comment by DavidRayner** [comment]
Now that Chrome 69 has a stable release can you update the Chrome web store version please :)

**Comment by KeenRivals** [comment]
I will probably follow the path I did last time and keep the old theme for a few weeks so most Chromes can update first. The new theme will look very bad on old chromes so I want to avoid that.
